    # readme.html 与 license.txt 直接暴露 WordPress 版本号，默认不对外提供。
    location ~* ^/wp/(readme\.html|license\.txt)$ {
        return 404;
    }

    location /wp/ {
        try_files $uri $uri/ /wp/index.php?$args;
    }

    # Add trailing slash to */wp-admin requests.
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
